name: Second Use Case

on: workflow_dispatch

jobs:
  manual-trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Print messages
      run: |
        echo "This is second use-case"
        echo "hi"
